const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let data=structuredClone(ORIGINAL),selected=null,tab='curriculum';try{const saved=JSON.parse(localStorage.getItem('surf-curriculum-v1'));if(Array.isArray(saved)&&saved.length)data=saved}catch(e){}
function save(){try{localStorage.setItem('surf-curriculum-v1',JSON.stringify(data));$('status').textContent='Saved on this browser.'}catch(e){$('status').textContent='Browser storage unavailable. Export a backup to keep these changes.'}}
function options(id,values,first){const old=$(id).value;$(id).innerHTML=(first?'<option value="">'+first+'</option>':'')+values.map(v=>`<option>${esc(v)}</option>`).join('');if(values.includes(old))$(id).value=old}
function init(){options('age',[...new Set(data.map(r=>r.age))].sort((a,b)=>(parseInt(a.slice(1))||99)-(parseInt(b.slice(1))||99)));if(!selected)$('age').value=data.some(r=>r.age.startsWith('U15'))?data.find(r=>r.age.startsWith('U15')).age:data[0].age;options('cycle',[...new Set(data.map(r=>r.cycle))].sort(),'All cycles');options('theme',[...new Set(data.map(r=>r.theme))].sort(),'All themes');render()}
function start(r){const m=r.week.match(/\d+\/\d+\/\d+/);return m?new Date(m[0]).getTime():0}
function render(){const q=$('search').value.toLowerCase(),rows=data.filter(r=>r.age===$('age').value&&(!$('cycle').value||r.cycle===$('cycle').value)&&(!$('theme').value||r.theme===$('theme').value)&&Object.values(r).join(' ').toLowerCase().includes(q)).sort((a,b)=>start(a)-start(b));if(!rows.some(r=>r.id===selected)){const next=rows.find(r=>start(r)>=new Date('2026-10-05').getTime());selected=(next||rows[0])?.id}$('count').textContent=rows.length+' calendar entries';$('list').innerHTML=rows.map(r=>`<button class="row ${r.id===selected?'active':''}" data-id="${r.id}"><small>${esc(r.week)}</small><strong>${esc(r.theme)}</strong><small>${esc(r.cycle)}</small><small>${esc(r.tactical)}</small></button>`).join('');document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{selected=b.dataset.id;render()});detail()}
function field(r,key,label){return `<label>${label}<textarea data-field="${key}">${esc(r[key])}</textarea></label>`}
function sessionLinks(r){return /^U(15|16)\b/.test(r.age)&&/10\/0?5\/26/.test(r.week)?`<div class="session-banner"><strong>This week's coached sessions · October 6–7</strong><p>Tuesday's teaching plan and Wednesday's progression, with PDF diagrams and group-specific coaching.</p>${WEEK_SESSIONS.map(s=>`<a class="pdf-link" href="${esc(s.pdf)}" target="_blank" rel="noopener">${esc(s.day)} PDF</a>`).join('')}<button id="open-week-from-entry">View session details</button></div>`:''}
function detail(){const r=data.find(r=>r.id===selected);if(!r){$('detail').innerHTML='<div class="card">No matching entries.</div>';return}$('detail').innerHTML=`<div class="card"><span class="pill">${esc(r.age)}</span> <span class="pill">${esc(r.year)}</span><h2>${esc(r.theme)} · ${esc(r.cycle)}</h2><label>Calendar week<input data-field="week" value="${esc(r.week)}"></label><nav>${['curriculum','sessions','diagram'].map(t=>`<button data-tab="${t}" aria-pressed="${tab===t}">${t[0].toUpperCase()+t.slice(1)}</button>`).join('')}<button id="print">Print entry</button></nav><div id="panel"></div></div>`;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;detail()});$('print').onclick=()=>window.print();
if(tab==='curriculum')$('panel').innerHTML=`<div class="fields">${[['tactical','Tactical focus'],['technical','Technical focus'],['goal','Strategic goal'],['vocabulary','Vocabulary'],['fix','On-field fixes and cues'],['metric','Success metric']].map(([k,l])=>field(r,k,l)).join('')}</div><h3>Suggested activities</h3>${field(r,'activities','Source activity bank')}${field(r,'notes','Your adaptations and observations')}`;
if(tab==='sessions')$('panel').innerHTML=`<p class="note">These are your imported outlines. Full-pitch activities and player counts may need adapting to your available space. Empty outlines are marked below.</p>${[['circuit','Circuit training'],['session1','Team training 1'],['session2','Team training 2']].map(([k,l])=>`<h3>${l}</h3>${!r[k]?'<p class="muted">No outline supplied for this entry. Add one below.</p>':''}${field(r,k,'Edit outline')}`).join('')}<details><summary>Build a suggested 90-minute session from this week</summary><p class="muted">Suggested structure, not an imported session. Adjust timing for younger players.</p><p>15 min: Ball-based activation using the weekly technical focus.<br>20 min: Technical activity with opposition.<br>25 min: Directional tactical game linked to the strategic goal.<br>20 min: Conditioned match using the weekly success metric.<br>10 min: Review, recovery, and player questions.</p>${field(r,'adaptedSession','Your complete session plan')}</details>`;
if(tab==='sessions')$('panel').insertAdjacentHTML('afterbegin',sessionLinks(r));if($('open-week-from-entry'))$('open-week-from-entry').onclick=()=>showWeek();
if(tab==='diagram')diagram(r);document.querySelectorAll('[data-field]').forEach(el=>el.onchange=()=>{r[el.dataset.field]=el.value;save();if(el.dataset.field==='week')render()})}
function diagram(r){if(!r.board)r.board={width:36,height:30,items:[],lines:[]};const b=r.board;$('panel').innerHTML=`<p class="muted">Build a diagram for this calendar entry. Tap a tool, then tap the pitch. Drag players or cones to reposition them. For a pass or run, tap the start and end points.</p><div class="controls"><label>Width (yards)<input id="width" type="number" min="5" max="120" value="${b.width}"></label><label>Height (yards)<input id="height" type="number" min="5" max="120" value="${b.height}"></label><label>Player label<input id="number" value="6" maxlength="8"></label></div><div class="controls">${['White','Pink','Yellow','Cone','Pass','Run','Move','Delete'].map(t=>`<button data-tool="${t}">${t}</button>`).join('')}<button id="undo">Undo last addition</button></div><p id="toolLabel" class="muted">Selected: White</p><svg id="pitch" viewBox="0 0 ${b.width*10} ${b.height*10}" aria-label="Editable soccer session diagram"></svg>${field(r,'diagramNotes','Diagram setup and scoring instructions')}`;let tool='White',anchor=null,drag=null;document.querySelectorAll('[data-tool]').forEach(el=>el.onclick=()=>{tool=el.dataset.tool;anchor=null;$('toolLabel').textContent='Selected: '+tool});
function draw(){const w=b.width*10,h=b.height*10;$('pitch').setAttribute('viewBox',`0 0 ${w} ${h}`);$('pitch').innerHTML=`<defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><path d="M0 0 L10 5 L0 10Z" fill="white"/></marker></defs><rect x="5" y="5" width="${w-10}" height="${h-10}" fill="none" stroke="white"/><path d="M${w/2} 5V${h-5}" stroke="#ffffff55"/>`+b.lines.map(l=>`<line x1="${l.x*w}" y1="${l.y*h}" x2="${l.x2*w}" y2="${l.y2*h}" stroke="white" stroke-width="2" ${l.type==='Run'?'stroke-dasharray="5 4"':''} marker-end="url(#arrow)"/>`).join('')+b.items.map((p,i)=>`<g data-player="${i}">${p.type==='Cone'?`<path d="M${p.x*w} ${p.y*h-6}l6 12h-12Z" fill="#ffb54f"/>`:`<circle cx="${p.x*w}" cy="${p.y*h}" r="10" fill="${{White:'#fff',Pink:'#f583b7',Yellow:'#ffdc54'}[p.type]}" stroke="#142c42"/><text x="${p.x*w}" y="${p.y*h+3}" text-anchor="middle" font-size="8" font-weight="bold" fill="#142c42">${esc(p.label)}</text>`}</g>`).join('')}
function point(e){const svg=$('pitch'),p=svg.createSVGPoint();p.x=e.clientX;p.y=e.clientY;const t=p.matrixTransform(svg.getScreenCTM().inverse());return{x:Math.max(.04,Math.min(.96,t.x/(b.width*10))),y:Math.max(.04,Math.min(.96,t.y/(b.height*10)))}}
$('pitch').onpointerdown=e=>{const hit=e.target.closest('[data-player]');if(tool==='Move'&&hit){drag=Number(hit.dataset.player);$('pitch').setPointerCapture(e.pointerId);return}if(tool==='Delete'){if(hit)b.items.splice(Number(hit.dataset.player),1);else b.lines.pop();draw();save();return}const p=point(e);if(tool==='Pass'||tool==='Run'){if(anchor){b.lines.push({...anchor,x2:p.x,y2:p.y,type:tool});anchor=null}else{anchor=p;$('toolLabel').textContent='Tap the end point';return}}else if(tool!=='Move'){b.items.push({...p,type:tool,label:$('number').value})}draw();save()};$('pitch').onpointermove=e=>{if(drag!==null){Object.assign(b.items[drag],point(e));draw()}};$('pitch').onpointerup=()=>{if(drag!==null){drag=null;save()}};$('undo').onclick=()=>{if(b.items.length)b.items.pop();else b.lines.pop();draw();save()};['width','height'].forEach(k=>$(k).onchange=()=>{b[k]=Math.max(5,Math.min(120,Number($(k).value)||30));draw();save()});draw()}
['age','cycle','theme'].forEach(id=>$(id).onchange=render);$('search').oninput=render;
$('export').onclick=()=>{const blob=new Blob([JSON.stringify({schema:1,entries:data},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='Surf_Coaching_Backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
$('import').onchange=async e=>{try{const backup=JSON.parse(await e.target.files[0].text());if(backup.schema!==1||!Array.isArray(backup.entries)||!backup.entries.length||!backup.entries.every(r=>typeof r.id==='string'&&['age','week','cycle','theme'].every(k=>typeof r[k]==='string')))throw Error('Invalid backup');if(!confirm('Replace this browser’s curriculum with the imported backup? Export current changes first if needed.'))return;data=backup.entries;selected=null;save();init()}catch(err){$('status').textContent='Could not import: '+err.message}e.target.value=''};init();

let coachingGroup='U15';
function showWeek(){
$('analysis-panel').classList.add('hidden');
$('calendar-layout').classList.add('hidden');$('week-panel').classList.remove('hidden');
$('week-panel').innerHTML=`<div class="card"><span class="pill">Cycle 3 · Deceptive Possession</span><h2>U15 + U16 · October 5–11, 2026</h2><p>90-minute shared sessions · U15: 16 players · U16: 18 players · 35 × 30-yard maximum</p><div class="controls"><button id="lens-u15" aria-pressed="${coachingGroup==='U15'}">U15 coaching points</button><button id="lens-u16" aria-pressed="${coachingGroup==='U16'}">U16 coaching points</button></div><button id="weekly-team-analysis">View ${coachingGroup} tactical analysis and training links</button><p class="muted">Wednesday uses the latest progressed plan. PDFs include the original exercise diagrams. Personal adaptations save in your curriculum entries.</p></div><div class="week-grid">${WEEK_SESSIONS.map(s=>`<article class="card session-head"><span class="pill">${esc(s.date)}</span><h2>${esc(s.day)}<br>${esc(s.title)}</h2><p><strong>${esc(s.principle)}</strong></p><a class="pdf-link" href="${esc(s.pdf)}" target="_blank" rel="noopener">Open PDF with diagrams</a><a class="pdf-link" href="${esc(s.pdf)}" download>Download PDF</a><h3>${coachingGroup} coaching emphasis</h3><div class="coaching-lens"><ul>${s[coachingGroup.toLowerCase()].map(n=>`<li>${esc(n)}</li>`).join('')}</ul></div><h3>Session activities</h3>${s.phases.map(p=>`<details class="phase"><summary>${esc(p[0])} · ${esc(p[1])}</summary><p>${esc(p[2])}</p><p><strong>Scoring / progression:</strong> ${esc(p[3])}</p><p><strong>Coach:</strong> ${esc(p[4])}</p></details>`).join('')}<details><summary>View original diagram pages</summary>${s.pages.map((p,i)=>`<img class="pdf-page" src="${esc(p)}" alt="${esc(s.day)} session plan and exercise diagrams, page ${i+1}" loading="lazy">`).join('')}</details></article>`).join('')}</div>`;
$('weekly-team-analysis').onclick=()=>showAnalysis(coachingGroup);
$('lens-u15').onclick=()=>{coachingGroup='U15';showWeek()};$('lens-u16').onclick=()=>{coachingGroup='U16';showWeek()};
}
$('show-week').onclick=()=>{coachingGroup=$('age').value.startsWith('U16')?'U16':'U15';showWeek()};
$('show-curriculum').onclick=()=>{$('analysis-panel').classList.add('hidden');$('week-panel').classList.add('hidden');$('calendar-layout').classList.remove('hidden')};

function showAnalysis(team,weekId){
const weeks=TEAM_ANALYSES.filter(a=>a.team===team).sort((a,b)=>b.weekId.localeCompare(a.weekId));
const a=weeks.find(a=>a.weekId===weekId)||weeks[0];
$('calendar-layout').classList.add('hidden');$('week-panel').classList.add('hidden');$('analysis-panel').classList.remove('hidden');
if(!a){$('analysis-panel').innerHTML='<div class="card">No film analysis has been added for this team yet.</div>';return;}
$('analysis-panel').innerHTML=`<div class="card"><div class="analysis-team-nav"><button id="analysis-u15" aria-pressed="${team==='U15'}">U15</button><button id="analysis-u16" aria-pressed="${team==='U16'}">U16</button><label>Review week<select id="analysis-week">${weeks.map(w=>`<option value="${esc(w.weekId)}" ${w.weekId===a.weekId?'selected':''}>${esc(w.week)}</option>`).join('')}</select></label></div><h2>${esc(a.team)} weekly tactical analysis</h2><span class="pill">${esc(a.week)}</span> <span class="pill">Surf vs ${esc(a.opponent)}</span><h3>${esc(a.headline)}</h3><p>${esc(a.basis)}</p><a class="pdf-link" href="${esc(a.report)}" target="_blank" rel="noopener">Open team film report</a><button id="analysis-to-training">View this week's training sessions</button></div><h2>Areas of growth</h2><div class="week-grid">${a.growth.map(g=>`<article class="card analysis-growth"><h3>${esc(g.title)}</h3><p>${esc(g.text)}</p><p class="analysis-evidence"><strong>Film / report reference:</strong> ${esc(g.evidence)}</p></article>`).join('')}</div><h2>Areas needing development</h2>${a.development.map(d=>`<article class="card analysis-development"><h3>${esc(d.title)}</h3><p>${esc(d.need)}</p><p class="analysis-evidence"><strong>Film / report reference:</strong> ${esc(d.evidence)}</p><div class="training-map"><h3>How this week's training feeds the development</h3><p><strong>Training objective:</strong> ${esc(d.objective)}</p>${d.training.map(([name,reason])=>`<p><strong>${esc(name)}</strong><br>${esc(reason)}</p>`).join('')}</div><p><strong>What to look for in the next film review:</strong> ${esc(d.watch)}</p><p><strong>Player cue:</strong> ${esc(d.cue)}</p></article>`).join('')}<p class="muted">Film findings come from the linked team report. Exercise links and next-review indicators are coaching applications, not evidence that training has already produced an improvement. New weekly reviews are added when updated film analysis is available.</p>`;
$('analysis-u15').onclick=()=>showAnalysis('U15',a.weekId);$('analysis-u16').onclick=()=>showAnalysis('U16',a.weekId);$('analysis-week').onchange=e=>showAnalysis(team,e.target.value);$('analysis-to-training').onclick=()=>{coachingGroup=team;showWeek()};
}
$('show-u15-analysis').onclick=()=>showAnalysis('U15');$('show-u16-analysis').onclick=()=>showAnalysis('U16');
